"use client";
import { useState } from "react";
import QRCode from "qrcode";
export default function EventPage() {
  const [session,setSession]=useState<any>(null),[qr,setQr]=useState(""),[error,setError]=useState(""),[location,setLocation]=useState("Hastings");
  const [showTuesday,setShowTuesday]=useState(false),[events,setEvents]=useState<any[]>([]),[name,setName]=useState(""),[startsAt,setStartsAt]=useState(""),[theme,setTheme]=useState("pauls"),[bartenderKey,setBartenderKey]=useState("");
  async function show(next:any){setSession(next);setQr(await QRCode.toDataURL(`${window.location.origin}/event/join?game=${next.session_code}`,{width:360,margin:2}));}
  function openDisplay(){if(session?.session_code) window.open(`/event/display?game=${encodeURIComponent(session.session_code)}`,"_blank","noopener,noreferrer");}
  async function joinInProgress(){setError("");const r=await fetch(`/api/no-gm/bartender?location=${encodeURIComponent(location)}`);const d=await r.json();if(!r.ok)setError(d.error||"Could not look up an active game.");else if(!d.session)setError(`There is no active game at ${location}.`);else show(d.session);}
  async function createEvent(){const r=await fetch("/api/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({location,hostName:"Bartender"})});const d=await r.json();if(!r.ok)setError(d.error||"Could not start game.");else show(d.session);}
  async function bartender(action:string){const r=await fetch("/api/no-gm/bartender",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,location,sessionId:session?.id})});const d=await r.json();if(!r.ok)setError(d.error||"Could not update games.");else alert(d.message||"Done.");}
  const bartenderHeaders={"Content-Type":"application/json","x-bartender-key":bartenderKey};
  async function loadTuesday(){const r=await fetch(`/api/trivia-tuesday?location=${encodeURIComponent(location)}`,{headers:{"x-bartender-key":bartenderKey}});const d=await r.json();if(!r.ok){if(bartenderKey)setError(d.error||"Could not load Trivia Tuesday.");}else setEvents(d.events||[]);}
  async function createTuesday(){const r=await fetch("/api/trivia-tuesday",{method:"POST",headers:bartenderHeaders,body:JSON.stringify({action:"create",location,eventName:name,scheduledStartAt:startsAt,boardTheme:theme})});const d=await r.json();if(!r.ok)setError(d.error||"Could not create Trivia Tuesday.");else {setName("");setStartsAt("");await loadTuesday();alert(`Created ${d.event.event_name}.  Fill in the ${d.sheetName} tab in the Google Sheet.`);}}
  async function launchTuesday(eventId:string,action:"start"|"test"){const r=await fetch("/api/trivia-tuesday",{method:"POST",headers:bartenderHeaders,body:JSON.stringify({action,eventId})});const d=await r.json();if(!r.ok)setError(d.error||"Could not launch Trivia Tuesday.");else show(d.session);}
  return <main className="event-shell"><h1>PCL Trivia Night</h1><h2>Bartender Console</h2><section className="event-card"><label>Location<select value={location} onChange={(e)=>setLocation(e.target.value)}><option>Hastings</option><option>Norfolk</option></select></label><button onClick={createEvent}>Start Trivia Night</button><button className="event-outline-button" onClick={joinInProgress}>Join game in progress</button><a className="event-secondary-link" href="/event-trivia">Start Event Trivia</a><button className="event-outline-button" onClick={()=>setShowTuesday(!showTuesday)}>Trivia Tuesday</button></section>
  {showTuesday&&<section className="event-card"><h2>Trivia Tuesday · {location}</h2><label>Bartender access key<input type="password" value={bartenderKey} onChange={(e)=>setBartenderKey(e.target.value)} placeholder="Enter the console key"/></label><button disabled={!bartenderKey} onClick={loadTuesday}>Refresh events</button><h3>Create new Trivia Tuesday</h3><label>Event name<input value={name} onChange={(e)=>setName(e.target.value)} placeholder="October Trivia Tuesday"/></label><label>Date and time<input type="datetime-local" value={startsAt} onChange={(e)=>setStartsAt(e.target.value)}/></label><label>Board theme<select value={theme} onChange={(e)=>setTheme(e.target.value)}><option value="pauls">Paul’s Classic</option><option value="autumn">Autumn</option><option value="halloween">Halloween</option><option value="holiday">Holiday</option></select></label><button disabled={!bartenderKey||!name.trim()||!startsAt} onClick={createTuesday}>Create Trivia Tuesday</button><h3>Play Trivia Tuesday</h3>{events.length===0?<p>Enter the bartender key and refresh to see scheduled events for {location}.</p>:events.map((event)=><div key={event.id} className="event-card"><strong>{event.event_name}</strong><p>{new Date(event.scheduled_start_at).toLocaleString("en-US",{timeZone:"America/Chicago",dateStyle:"medium",timeStyle:"short"})} · {event.board_theme}</p><p>Status: {event.status}</p><button disabled={!bartenderKey} onClick={()=>launchTuesday(event.id,"test")}>Test game</button><button disabled={!bartenderKey||event.status==="completed"||Date.now()<new Date(event.scheduled_start_at).getTime()-7200000} onClick={()=>launchTuesday(event.id,"start")}>{event.status==="completed"?"Played":"Start Trivia"}</button></div>)}</section>}
  {session&&<section className="event-card"><h2>{session.is_test?"TEST GAME · ":""}Game #{session.session_code}</h2>{qr&&<img src={qr} alt="Join game QR code" style={{maxWidth:"100%"}}/>}<button onClick={openDisplay}>Show display screen</button><button onClick={()=>bartender("end_current")}>End current game</button></section>}<section className="event-card"><h2>Game tools</h2><button onClick={()=>bartender("end_all")}>End all active games at {location}</button><button className="event-outline-button" onClick={()=>bartender("reset_questions")}>Reset {location} question history</button></section><section className="event-card"><h2>Leaderboards</h2><a className="event-secondary-link" href="/history">View all leaderboards</a></section>{error&&<p className="event-error">{error}</p>}</main>;
}
