"use client";

import { useState } from "react";
import QRCode from "qrcode";

export default function EventPage() {
  const [session, setSession] = useState<any>(null); const [qr, setQr] = useState(""); const [error, setError] = useState(""); const [location, setLocation] = useState("Hastings");
  async function show(sessionToShow: any) { setSession(sessionToShow); setQr(await QRCode.toDataURL(`${window.location.origin}/event/join?game=${sessionToShow.session_code}`, { width: 360, margin: 2 })); }
  function openDisplay() { if (!session?.session_code) return; window.open(`/event/display?game=${encodeURIComponent(session.session_code)}`, "_blank", "noopener,noreferrer"); }
  async function createEvent() { const response = await fetch("/api/sessions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ location, hostName: "Bartender" }) }); const data = await response.json(); if (!response.ok) setError(data.error || "Could not start game."); else show(data.session); }
  async function bartender(action: string) { const response = await fetch("/api/no-gm/bartender", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, location, sessionId: session?.id }) }); const data = await response.json(); if (!response.ok) setError(data.error || "Could not update games."); else alert(data.message || "Done."); }
  return <main className="event-shell"><h1>PCL Trivia Night</h1><h2>Bartender Console</h2><section className="event-card"><label>Location<select value={location} onChange={(event) => setLocation(event.target.value)}><option>Hastings</option><option>Norfolk</option></select></label><button onClick={createEvent}>Start Trivia Night</button><a className="event-secondary-link" href="/event-trivia">Start Event Trivia</a></section>{session && <section className="event-card"><h2>Game #{session.session_code}</h2>{qr && <img src={qr} alt="Join game QR code" style={{ maxWidth: "100%" }} />}<button onClick={openDisplay}>Show display screen</button><button onClick={() => bartender("end_current")}>End current game</button></section>}<section className="event-card"><h2>Game tools</h2><button onClick={() => bartender("end_all")}>End all active games at {location}</button><button className="event-outline-button" onClick={() => bartender("reset_questions")}>Reset {location} question history</button></section><section className="event-card"><h2>Leaderboards</h2><a className="event-secondary-link" href="/history">View all leaderboards</a></section>{error && <p className="event-error">{error}</p>}</main>;
}
