import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ButtonClickFeedback from './ButtonClickFeedback';

const inter = Inter({ subsets: ['latin'] });
// Keep the permanent Paul’s styles in globals.css.  Event looks are additive layers.
const activeEventTemplate = 'roper-romp-template';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${activeEventTemplate}`}>
        <ButtonClickFeedback />
        {children}
      </body>
    </html>
  );
}
