"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import QRCode from "qrcode";

export default function EventDisplayPage() {
  const code = useSearchParams().get("game") || ""; const [state, setState] = useState<any>(null); const [qr, setQr] = useState(""); const [now, setNow] = useState(Date.now());
  useEffect(() => { let id: any; async function load() { const found = await (await fetch(`/api/session-by-code?sessionCode=${encodeURIComponent(code)}`)).json(); if (!found.session) return; const data = await (await fetch(`/api/no-gm/state?sessionId=${found.session.id}`)).json(); setState(data); } load(); id = setInterval(load, 2500); return () => clearInterval(id); }, [code]);
  useEffect(() => { if (!state?.session?.session_code) return; QRCode.toDataURL(`${window.location.origin}/event/join?game=${state.session.session_code}`, { width: 180, margin: 1 }).then(setQr); }, [state?.session?.session_code]);
  useEffect(() => { const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []);
  if (!state?.session) return <main className="event-display roper-trivia-display"><h1>Roper Trivia</h1><p>Loading game…</p></main>;
  const { session, control, players, leaderboardExport, lastCall, dispute } = state; const lastCallSeconds = lastCall?.game?.phase === "voting" || lastCall?.game?.phase === "wagering" ? 45 : lastCall?.game?.phase === "question" ? 60 : lastCall?.game?.phase === "reveal" ? 3 : 10; const phaseEndsAt = lastCall ? new Date(new Date(lastCall.game.phase_started_at).getTime() + lastCallSeconds * 1000).toISOString() : dispute?.closes_at || session.question_ends_at; const seconds = phaseEndsAt ? Math.max(0, Math.ceil((new Date(phaseEndsAt).getTime() - now) / 1000)) : null; return <main className="event-display roper-trivia-display"><div className="event-display-qr">{qr && <img src={qr} alt={`Join game ${session.session_code}`} />}<strong>Scan to join · Game #{session.session_code}</strong></div><p className="roper-trivia-kicker">Paul&apos;s Cigar Lounge presents</p><h1>Roper Trivia · Game #{session.session_code}</h1>{control?.state === "ended" ? <h2>Game complete</h2> : session.game_mode === "last_call" && lastCall ? <><h2>{lastCall.game.phase === "question" ? lastCall.game.question_text : `Last Call: ${lastCall.game.phase}`}</h2><p>{seconds}s remaining</p>{["reveal", "complete"].includes(lastCall.game.phase) && <p className="event-answer">Answer: {lastCall.game.correct_answer}</p>}</> : <><h2>{session.current_question_text || "Players are joining…"}</h2>{session.question_status === "revealed" && <p className="event-answer">Answer: {session.current_answer}</p>}{dispute && <p>Answer under review · {seconds}s remaining</p>}<p>{seconds === null ? "" : `${seconds}s remaining`}</p></>}<ol>{(leaderboardExport?.leaderboard || players || []).map((player: any) => <li key={player.id}>{player.display_name} <strong>{player.score}</strong></li>)}</ol></main>;
}
