"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import QRCode from "qrcode";
export default function EventDisplayPage() {
  const code=useSearchParams().get("game")||"";const [state,setState]=useState<any>(null),[qr,setQr]=useState(""),[now,setNow]=useState(Date.now());
  useEffect(()=>{let id:any;async function load(){const found=await(await fetch(`/api/session-by-code?sessionCode=${encodeURIComponent(code)}`)).json();if(!found.session)return;setState(await(await fetch(`/api/no-gm/state?sessionId=${found.session.id}`)).json());}load();id=setInterval(load,2500);return()=>clearInterval(id);},[code]);
  useEffect(()=>{if(state?.session?.session_code)QRCode.toDataURL(`${window.location.origin}/event/join?game=${state.session.session_code}`,{width:180,margin:1}).then(setQr);},[state?.session?.session_code]);
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[]);
  if(!state?.session)return <main className="event-display"><h1>PCL Trivia Night</h1><p>Loading game…</p></main>;
  const {session,control,players,leaderboardExport,lastCall,dispute,rickhouse}=state;const ends=dispute?.closes_at||session.question_ends_at;const seconds=ends?Math.max(0,Math.ceil((new Date(ends).getTime()-now)/1000)):null; const themed=`event-display ${session.is_test?"trivia-test-display":""} ${session.trivia_tuesday_theme?`trivia-theme-${session.trivia_tuesday_theme}`:""}`;
  const board=rickhouse&&rickhouse.game.game_phase==="board"?<section><h2>{rickhouse.game.round_name==="single_cask"?"Single Cask":"Double Cask"}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:"0.5rem"}}>{[0,1,2,3,4].map(c=><div key={c}><strong>{rickhouse.pours.find((p:any)=>p.column_index===c)?.category||""}</strong>{[0,1,2,3,4].map(row=>{const pour=rickhouse.pours.find((p:any)=>p.column_index===c&&p.row_index===row);return <div key={row} style={{padding:"0.5rem",margin:"0.25rem",border:"1px solid #b08a36",opacity:pour?.is_used ? 0.7 : 1}}>{pour?.is_used?"—":pour?.point_value}</div>;})}</div>)}</div></section>:null;
  return <main className={themed}><div className="event-display-qr">{qr&&<img src={qr} alt={`Join game ${session.session_code}`}/>}<strong>Scan to join · Game #{session.session_code}</strong></div><p>Paul&apos;s Cigar Lounge presents</p><h1>{session.is_test?"TEST GAME · ":""}PCL Trivia Night · Game #{session.session_code}</h1>{control?.state==="ended"?<h2>Game complete</h2>:board||<><h2>{session.current_question_text||"Players are joining…"}</h2>{session.question_status==="revealed"&&<p className="event-answer">Answer: {session.current_answer}</p>}{dispute&&<p>Answer under review · {seconds}s remaining</p>}<p>{seconds===null?"":`${seconds}s remaining`}</p></>}<ol>{(leaderboardExport?.leaderboard||players||[]).map((p:any)=><li key={p.id}>{p.display_name} <strong>{p.score}</strong></li>)}</ol></main>;
}
