"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { anonymousAccessToken } from "@/lib/browserSupabase";

export default function EventPlayPage() {
  const params = useSearchParams(); const sessionId = params.get("sessionId") || ""; const playerId = params.get("playerId") || ""; const [state, setState] = useState<any>(null); const [answer, setAnswer] = useState(""); const [error, setError] = useState(""); const [now, setNow] = useState(Date.now());
  const request = async (path: string, body?: any) => { const token = await anonymousAccessToken(); return fetch(path, { method: body ? "POST" : "GET", headers: body ? { "Content-Type": "application/json", Authorization: `Bearer ${token}` } : { Authorization: `Bearer ${token}` }, body: body ? JSON.stringify(body) : undefined }); };
  const refresh = async () => { if (!sessionId) return; const response = await request(`/api/no-gm/state?sessionId=${sessionId}`); const data = await response.json(); setState(data); if (data?.control?.decision_player_id === playerId && data?.control?.state === "main_active") await request("/api/no-gm/tick", { sessionId }); };
  useEffect(() => { refresh(); const id = setInterval(refresh, 2500); const clock = setInterval(() => setNow(Date.now()), 1000); return () => { clearInterval(id); clearInterval(clock); }; }, [sessionId]);
  useEffect(() => { if (state?.control?.decision_player_id === playerId && state?.control?.state === "main_active") request("/api/no-gm/tick", { sessionId }).then(refresh); }, [state?.session?.question_status, state?.control?.state, playerId]);
  useEffect(() => { if (state?.control?.state === "timeout" && state.control.timeout_at && Date.now() - new Date(state.control.timeout_at).getTime() >= 30 * 60 * 1000) action("/api/no-gm/control", { sessionId, action: "finalize_timeout" }); }, [state?.control?.state, state?.control?.timeout_at]);
  async function action(path: string, body: any) { setError(""); const response = await request(path, body); const data = await response.json(); if (!response.ok) setError(data.error || "Could not complete that action."); else { setAnswer(""); refresh(); } }
  if (!state?.session || !state?.control) return <main className="event-shell"><p>Loading game…</p></main>;
  const { session, control, players, dispute, leaderboardExport, myAnswer } = state; const isDecision = control.decision_player_id === playerId; const seconds = session.question_ends_at ? Math.max(0, Math.ceil((new Date(session.question_ends_at).getTime() - now) / 1000)) : 0;
  return <main className="event-shell"><h1>PCL Trivia · Game #{session.session_code}</h1><p>{isDecision ? "You are the decision player." : "The decision player starts the game and keeps it moving."}</p>{control.state === "lobby" && <section className="event-card"><h2>Ready to play?</h2>{isDecision ? <button onClick={() => action("/api/no-gm/control", { sessionId, action: "start_main" })}>Start Main Trivia</button> : <p>Waiting for Player 1 to choose Main Trivia.</p>}</section>}{control.state === "main_active" && <section className="event-card"><p className="event-timer">{session.question_status === "active" ? `${seconds}s` : session.question_status === "revealed" ? "Answer revealed" : "Next question loading…"}</p><h2>{session.current_question_text || "Get ready…"}</h2>{session.current_category && <p>{session.current_category} · {session.current_difficulty}</p>}{session.question_status === "active" && (myAnswer ? <p className="event-locked-answer"><strong>Your locked answer:</strong> {myAnswer.submitted_answer}</p> : <form onSubmit={(e) => { e.preventDefault(); action("/api/no-gm/answer", { sessionId, submittedAnswer: answer }); }}><input value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Your answer" required /><button>Lock answer</button></form>)}{session.question_status === "revealed" && <><p><strong>Answer:</strong> {session.current_answer}</p>{myAnswer && <><p className="event-locked-answer"><strong>Your answer:</strong> {myAnswer.submitted_answer}</p><p className={myAnswer.is_correct ? "event-result-correct" : "event-result-wrong"}>{myAnswer.is_correct ? `Correct — +${myAnswer.points_awarded} point${myAnswer.points_awarded === 1 ? "" : "s"}` : "Not counted — 0 points"}</p></>}<button onClick={() => action("/api/no-gm/dispute", { sessionId, action: "open" })}>Dispute my last answer</button></>}{dispute && <div className="event-dispute"><strong>Answer under review</strong><p>Vote: should this answer count?</p><button onClick={() => action("/api/no-gm/dispute", { sessionId, action: "vote", disputeId: dispute.id, voteYes: true })}>Yes, count it</button><button onClick={() => action("/api/no-gm/dispute", { sessionId, action: "vote", disputeId: dispute.id, voteYes: false })}>No</button></div>}</section>}{control.state === "timeout" && <section className="event-card"><h2>Game timed out</h2><p>Touch Resume to keep playing. The person who resumes becomes the decision player.</p><button onClick={() => action("/api/no-gm/control", { sessionId, action: "resume" })}>Resume game</button></section>}{control.state === "ended" && <section className="event-card"><h2>Game complete</h2><p>Leaderboard exported and saved.</p></section>}<section className="event-card"><h2>Leaderboard</h2><ol>{(leaderboardExport?.leaderboard || players).map((player: any) => <li key={player.id}>{player.display_name}: {player.score}</li>)}</ol></section>{error && <p className="event-error">{error}</p>}</main>;
}
