"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { anonymousAccessToken } from "@/lib/browserSupabase";
import LastCallPanel from "../LastCallPanel";
import AgingRoomPanel from "../AgingRoomPanel";

export default function EventPlayPage() {
  const params = useSearchParams(); const sessionId = params.get("sessionId") || ""; const playerId = params.get("playerId") || "";
  const [state, setState] = useState<any>(null); const [answer, setAnswer] = useState(""); const [editing, setEditing] = useState(false); const [error, setError] = useState(""); const [now, setNow] = useState(Date.now());
  const request = async (path: string, body?: any) => { const token = await anonymousAccessToken(); return fetch(path, { method: body ? "POST" : "GET", headers: body ? { "Content-Type": "application/json", Authorization: `Bearer ${token}` } : { Authorization: `Bearer ${token}` }, body: body ? JSON.stringify(body) : undefined }); };
  const refresh = async () => { if (!sessionId) return; const response = await request(`/api/no-gm/state?sessionId=${sessionId}`); const data = await response.json(); setState(data); if (data?.control?.decision_player_id === playerId && data?.control?.state === "main_active") await request(data?.session?.game_mode === "last_call" ? "/api/no-gm/last-call/tick" : data?.session?.game_mode === "aging_room" ? "/api/no-gm/aging/tick" : "/api/no-gm/tick", { sessionId }); };
  useEffect(() => { refresh(); const poll = setInterval(refresh, 2500); const clock = setInterval(() => setNow(Date.now()), 1000); return () => { clearInterval(poll); clearInterval(clock); }; }, [sessionId]);
  useEffect(() => { setAnswer(""); setEditing(false); }, [state?.session?.current_question_id]);
  useEffect(() => { if (!error) return; const id = setTimeout(() => setError(""), 5000); return () => clearTimeout(id); }, [error]);
  async function action(path: string, body: any) { setError(""); const response = await request(path, body); const data = await response.json(); if (!response.ok) setError(data.error || "Could not complete that action."); else { if (path.includes("answer")) setAnswer(""); refresh(); } }
  useEffect(() => {
    if (!state?.session || state.session.question_status !== "active" || state?.myAnswer || !answer.trim()) return;
    const milliseconds = new Date(state.session.question_ends_at).getTime() - now;
    if (milliseconds <= 1000) action("/api/no-gm/answer", { sessionId, submittedAnswer: answer });
  }, [now, state?.session?.question_status, state?.session?.current_question_id]);
  if (!state?.session) return <main className="event-shell"><p>Loading game…</p></main>;
  if (!state.control) return <main className="event-shell"><h1>PCL Trivia · Game #{state.session.session_code}</h1><section className="event-card"><h2>Waiting for a Decision Player</h2><p>The first player chose to pass control.  The next player who joins can take it.</p></section></main>;
  const { session, control, players, dispute, leaderboardExport, myAnswer, lastCall, aging } = state; const isDecision = control.decision_player_id === playerId; const seconds = session.question_ends_at ? Math.max(0, Math.ceil((new Date(session.question_ends_at).getTime() - now) / 1000)) : 0;
  const submitAnswer = (event: React.FormEvent) => { event.preventDefault(); action("/api/no-gm/answer", { sessionId, submittedAnswer: answer, action: editing ? "replace" : undefined }); };
  return <main className="event-shell"><h1>PCL Trivia · Game #{session.session_code}</h1><p>{isDecision ? "You are the decision player." : "The decision player keeps the game moving."}</p>
    {control.state === "lobby" && <section className="event-card"><h2>Ready to play?</h2>{isDecision ? <><button onClick={() => action("/api/no-gm/control", { sessionId, action: "start_main" })}>Start Main Trivia</button><button onClick={() => action("/api/no-gm/aging", { sessionId, action: "start" })}>Start The Aging Room</button></> : <p>Waiting for the Decision Player.</p>}</section>}
    {control.state === "main_active" && session.game_mode === "last_call" && lastCall && <LastCallPanel lastCall={lastCall} submit={(actionName, value) => action("/api/no-gm/last-call", { sessionId, action: actionName, value })} />}
    {control.state === "main_active" && session.game_mode === "aging_room" && aging && <AgingRoomPanel aging={aging} submit={(value) => action("/api/no-gm/aging", { sessionId, action: "answer", answer: value })} />}
    {control.state === "main_active" && session.game_mode === "main" && <section className="event-card"><p className="event-timer">{session.question_status === "active" ? `${seconds}s` : session.question_status === "revealed" ? "Answer revealed" : "Next question loading…"}</p><h2>{session.current_question_text || "Get ready…"}</h2>{session.current_category && <p>{session.current_category} · {session.current_difficulty}</p>}
      {session.question_status === "active" && (myAnswer && !editing ? <><p className="event-locked-answer"><strong>Your locked answer:</strong> {myAnswer.submitted_answer}</p><button className="event-outline-button" onClick={() => { setAnswer(myAnswer.submitted_answer); setEditing(true); }}>Oh shit — change answer</button></> : <form onSubmit={submitAnswer}><input value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Your answer" required /><button>{editing ? "Replace locked answer" : "Lock answer"}</button></form>)}
      {session.question_status === "revealed" && <><p><strong>Answer:</strong> {session.current_answer}</p>{myAnswer && <><p className="event-locked-answer"><strong>Your answer:</strong> {myAnswer.submitted_answer}</p><p className={myAnswer.is_correct ? "event-result-correct" : "event-result-wrong"}>{myAnswer.is_correct ? `Correct — +${myAnswer.points_awarded} point${myAnswer.points_awarded === 1 ? "" : "s"}` : "Not counted — 0 points"}</p></>}<button onClick={() => action("/api/no-gm/dispute", { sessionId, action: "open" })}>Dispute my last answer</button></>}
      {dispute && <div className="event-dispute"><strong>Answer under review</strong><p>Vote: should this answer count?  A tied vote follows the controller’s vote.</p><button onClick={() => action("/api/no-gm/dispute", { sessionId, action: "vote", disputeId: dispute.id, voteYes: true })}>Yes, count it</button><button onClick={() => action("/api/no-gm/dispute", { sessionId, action: "vote", disputeId: dispute.id, voteYes: false })}>No</button></div>}
      {isDecision && <div className="event-button-row"><button onClick={() => action("/api/no-gm/control", { sessionId, action: "skip_question" })}>Everyone answered — reveal now</button><button className="event-outline-button" onClick={() => action("/api/no-gm/control", { sessionId, action: "end_mode" })}>End current mode</button><button onClick={() => action("/api/no-gm/control", { sessionId, action: "end_session" })}>End session → Last Call</button></div>}</section>}
    {control.state === "timeout" && <section className="event-card"><h2>Game timed out</h2><p>Touch Resume to keep playing.  The person who resumes becomes the Decision Player.</p><button onClick={() => action("/api/no-gm/control", { sessionId, action: "resume" })}>Resume game</button></section>}
    {control.state === "ended" && <section className="event-card"><h2>Game complete</h2><p>Leaderboard exported and saved.</p></section>}
    {isDecision && control.state !== "ended" && <section className="event-card"><h2>Decision Player controls</h2>{players.filter((player: any) => player.id !== playerId && !player.left_at).map((player: any) => <button key={player.id} className="event-outline-button" onClick={() => action("/api/no-gm/control", { sessionId, action: "pass_control", targetPlayerId: player.id })}>Pass control to {player.display_name}</button>)}<button onClick={() => action("/api/no-gm/control", { sessionId, action: "end_session" })}>End session → Last Call</button></section>}
    {control.state !== "ended" && <button className="event-outline-button" onClick={() => action("/api/no-gm/control", { sessionId, action: "leave" })}>Leave game session</button>}
    <section className="event-card"><h2>Leaderboard</h2><ol>{(leaderboardExport?.leaderboard || players).map((player: any) => <li key={player.id}>{player.display_name}{player.left_at ? " (left)" : ""}: {player.score}</li>)}</ol></section>{error && <p className="event-error">{error}</p>}</main>;
}
